name: conpassione/kvm-registrationform
typeField: type
typeName: kvm-registrationform
title: 'Sport-Registration Item'
table: tx_conpassione_registrationform
prefixFields: false
languageAware: false
labelField:
  - event
  - class
  - lastname
  - firstname
  - mobile
  - email
  - dog
security:
  ignorePageTypeRestriction: true

fields:
  - identifier: lastname
    type: Text
    label: 'Name'
    required: true
  - identifier: firstname
    type: Text
    label: 'Vorname'
  - identifier: street
    type: Text
    label: 'Strasse'
    required: true
  - identifier: city
    type: Text
    label: 'PLZ / Ort'
  - identifier: mobile
    type: Text
    label: 'Mobile'
  - identifier: email
    type: Text
    label: 'E-Mail'
    required: true
  - identifier: event
    type: Text
    label: 'Event'
    required: true
  - identifier: message
    type: Textarea
    label: 'Message'
    rows: 6
    enableRichtext: true
  - identifier: class
    type: Text
    label: 'Class'
  - identifier: dog
    type: Text
    label: 'Dog'
  - identifier: breed
    type: Text
    label: 'Breed'
  - identifier: birthdate
    type: DateTime
    label: 'Birthdate'
    format: date
  - identifier: skg
    type: Checkbox
    label: SKG-Mitglied
