name: conpassione/eventlist
typeName: eventlist
group: z-cpextensions
prefixFields: false
fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: cp_max_items
    type: Number
    defaultValue: 0
    range:
      lower: 0
      upper: 999
  - identifier: cp_archive
    type: Radio
    defaultValue: 0
    items:
      - label: 'aktuelle'
        value: 0
      - label: 'archivierte'
        value: 1
  - identifier: pages
    type: Relation
    allowed: 'pages'
    suggestOptions:
      additionalSearchFields: 'nav_title'
basics:
  - TYPO3/Appearance
  - TYPO3/Links
